# Generated by Django 4.0.4 on 2022-04-23 08:22

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='document',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=256, null=True, verbose_name='Documents'),
        ),
    ]
