# Generated by Django 4.0.4 on 2022-04-19 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/for_download', verbose_name='File to download')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number_of_downloads', models.PositiveIntegerField(default=0)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='site_info.tag')),
            ],
            options={
                'verbose_name': 'For download',
                'verbose_name_plural': 'For downloads',
            },
        ),
    ]
