# Generated by Django 4.0.4 on 2022-04-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0002_fordownload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='includearea',
            name='code',
            field=models.CharField(choices=[('advantages', 'Наши преимущества'), ('brands', 'Брэнды'), ('counter', 'Счетчик'), ('for_download', 'Для скачиваний')], default='advantages', help_text="<i>\nПринцип работы:<br> \n<b>advantages</b> - кодовое название Включаемой облости.<br>\nI.  Проинициализировать кодовое слово в ``CHOICES``(<b>advantages</b>).<br>\nII. Создать HTML шаблон с кодовым словом ~/include_area/templates/<b>advantages</b>.html<br>\nIII. Чтобы отображать его в любом месте сайта - нужно в HTML страницы/шаблона прописать тэг:<br>\n<code><small>{% get_include_area request code='<b>advantages</b>' %}</small></code>\n</i>", max_length=20, verbose_name='Код'),
        ),
    ]
