# Generated by Django 4.0.4 on 2022-04-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='default_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='layout',
            field=models.CharField(choices=[('product/templates/product_detail.html', 'Шаблон по умолчанию'), ('product/templates/product_detail_layout_dev.html', 'Шаблон на разработке'), ('product/templates/product_detail_layout_images_min_bottom.html', 'Шаблон: мини-изображения под главной фотографией')], default='product/templates/product_detail.html', max_length=256, verbose_name='Шаблоны страницы'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='text',
            field=models.TextField(verbose_name='Comments'),
        ),
    ]
