# Generated by Django 4.0.4 on 2022-04-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='unit',
            field=models.CharField(choices=[('pcs', 'шт.'), ('m', 'п.м'), ('sqm', 'м.кв'), ('cbm', 'м.куб'), ('not_show', ' - ')], default='pcs', max_length=12, verbose_name='Ед.изм'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommend_products',
            field=models.ManyToManyField(blank=True, help_text='Отображаются внизу карточки товара, как рекомендованные или похожие товары', limit_choices_to={'is_show': True}, to='catalog.product', verbose_name='Рекомендованные/Похожие'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='unit',
            field=models.CharField(choices=[('pcs', 'шт.'), ('m', 'п.м'), ('sqm', 'м.кв'), ('cbm', 'м.куб'), ('not_show', ' - ')], default='pcs', max_length=12, verbose_name='Ед.изм'),
        ),
        migrations.AlterField(
            model_name='productparam',
            name='bool_value',
            field=models.BooleanField(max_length=255, null=True, verbose_name='Значение(булево)'),
        ),
    ]
