# Generated by Django 4.0.4 on 2022-04-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_productitem_default_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
