# Generated by Django 4.0.4 on 2022-04-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('param', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramvalue',
            name='bool_value',
            field=models.BooleanField(max_length=255, null=True, verbose_name='Значение(булево)'),
        ),
    ]
